#!/bin/bash

set +x # Do not leak information

# Exit immediately if one of the files given as arguments is not there
# because we don't want to delete the existing release if we don't have
# the new files that should be uploaded 
for file in "$@"
do
    if [ ! -e "$file" ]
    then echo "$file is missing, giving up." >&2; exit 1
    fi
done

if [ $# -eq 0 ]; then
    echo "No artifacts to use for release, giving up."
    exit 0
fi

if command -v sha256sum >/dev/null 2>&1 ; then
  shatool="sha256sum"
elif command -v shasum >/dev/null 2>&1 ; then
  shatool="shasum -a 256" # macOS fallback
else
  echo "Neither sha256sum nor shasum is available, cannot check hashes"
fi

if [[ ${GITHUB_REF} == refs/heads/* ]]; then
  GITHUB_BRANCH=${GITHUB_REF##*/}
elif [[ ${GITHUB_REF} == refs/tags/* ]]; then
  GITHUB_TAG=${GITHUB_REF##*/}
fi

# The calling script (usually .travis.yml) can set a suffix to be used for
# the tag and release name. This way it is possible to have a release for
# the output of the CI/CD pipeline (marked as 'continuous') and also test
# builds for other branches.
# If this build was triggered by a tag, call the result a Release
if [ ! -z "$UPLOADTOOL_SUFFIX" ] ; then
  if [ "$UPLOADTOOL_SUFFIX" = "${GITHUB_TAG}" ] ; then
    RELEASE_NAME="${GITHUB_TAG}"
    RELEASE_TITLE="Release build (${GITHUB_TAG})"
    is_prerelease="false"
  else
    RELEASE_NAME="continuous-$UPLOADTOOL_SUFFIX"
    RELEASE_TITLE="Continuous build ($UPLOADTOOL_SUFFIX)"
    is_prerelease="true"
  fi
else
  if [ "${GITHUB_TAG}" != "" ]; then
    RELEASE_NAME="${GITHUB_TAG}"
    RELEASE_TITLE="Release build (${GITHUB_TAG})"
    is_prerelease="false"
  elif [ "${GITHUB_BRANCH}" != "" ] && [ "${GITHUB_BRANCH}" != "master" ]; then
    RELEASE_NAME="continuous-${GITHUB_BRANCH}"
    RELEASE_TITLE="Continuous build (${GITHUB_BRANCH})"
    is_prerelease="true"
  else
    RELEASE_NAME="continuous" # Do not use "latest" as it is reserved by GitHub
    RELEASE_TITLE="Continuous build"
    is_prerelease="true"
  fi
fi

# Do not upload non-master branch builds
if [ "${GITHUB_EVENT_NAME}" == "pull_request" ] ; then
  echo "Release uploading disabled for pull requests, uploading to transfer.sh instead"
  rm -f ./uploaded-to
  for FILE in "$@" ; do
    BASENAME="$(basename "${FILE}")"
    curl --upload-file $FILE "https://transfer.sh/$BASENAME" > ./one-upload
    echo "$(cat ./one-upload)" # this way we get a newline
    echo -n "$(cat ./one-upload)\\n" >> ./uploaded-to # this way we get a \n but no newline
  done
  $shatool "$@"
  exit 0
fi

tag_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/git/refs/tags/${RELEASE_NAME}"
tag_infos=$(curl -XGET --header "Authorization: token ${RELEASE_TOKEN}" "${tag_url}")
echo "tag_infos: $tag_infos"
tag_sha=$(echo "$tag_infos" | grep '"sha":' | head -n 1 | cut -d '"' -f 4 | cut -d '{' -f 1)
echo "tag_sha: $tag_sha"

release_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/tags/${RELEASE_NAME}"
echo "Getting the release ID..."
echo "release_url: $release_url"
release_infos=$(curl -XGET --header "Authorization: token ${RELEASE_TOKEN}" "${release_url}")
echo "release_infos: $release_infos"
release_id=$(echo "$release_infos" | grep "\"id\":" | head -n 1 | tr -s " " | cut -f 3 -d" " | cut -f 1 -d ",")
echo "release ID: $release_id"
upload_url=$(echo "$release_infos" | grep '"upload_url":' | head -n 1 | cut -d '"' -f 4 | cut -d '{' -f 1)
echo "upload_url: $upload_url"
release_url=$(echo "$release_infos" | grep '"url":' | head -n 1 | cut -d '"' -f 4 | cut -d '{' -f 1)
echo "release_url: $release_url"
target_commit_sha=$(echo "$release_infos" | grep '"target_commitish":' | head -n 1 | cut -d '"' -f 4 | cut -d '{' -f 1)
echo "target_commit_sha: $target_commit_sha"

if [ "${GITHUB_SHA}" != "$target_commit_sha" ] ; then

  echo "${GITHUB_SHA} != target_commit_sha, hence deleting ${RELEASE_NAME}..."
  
  if [ ! -z "$release_id" ]; then
    delete_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/$release_id"
    echo "Delete the release..."
    echo "delete_url: $delete_url"
    curl -XDELETE \
        --header "Authorization: token ${RELEASE_TOKEN}" \
        "${delete_url}"
  fi

  # echo "Checking if release with the same name is still there..."
  # echo "release_url: $release_url"
  # curl -XGET --header "Authorization: token ${RELEASE_TOKEN}" \
  #     "$release_url"

  if [ "$is_prerelease" = "true" ] ; then
    # if this is a continuous build tag, then delete the old tag
    # in preparation for the new release
    echo "Delete the tag..."
    delete_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/git/refs/tags/${RELEASE_NAME}"
    echo "delete_url: $delete_url"
    curl -XDELETE \
        --header "Authorization: token ${RELEASE_TOKEN}" \
        "${delete_url}"
  fi

  echo "Create release..."

  if [ -z "${GITHUB_BRANCH}" ] ; then
    {GITHUB_BRANCH}="master"
  fi

  if [ ! -z "${GITHUB_RUN_ID}" ] ; then
    if [ -z "${UPLOADTOOL_BODY+x}" ] ; then
      BODY="GitHub Actions build log: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
    else
      BODY="$UPLOADTOOL_BODY"
    fi
  else
    BODY="$UPLOADTOOL_BODY"
  fi

  release_infos=$(curl -H "Authorization: token ${RELEASE_TOKEN}" \
       --data '{"tag_name": "'"${RELEASE_NAME}"'","target_commitish": "'"${GITHUB_SHA}"'","name": "'"${RELEASE_TITLE}"'","body": "'"${BODY}"'","draft": false,"prerelease": '$is_prerelease'}' "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases")

  echo "$release_infos"

  unset upload_url
  upload_url=$(echo "$release_infos" | grep '"upload_url":' | head -n 1 | cut -d '"' -f 4 | cut -d '{' -f 1)
  echo "upload_url: $upload_url"

  unset release_url
  release_url=$(echo "$release_infos" | grep '"url":' | head -n 1 | cut -d '"' -f 4 | cut -d '{' -f 1)
  echo "release_url: $release_url"

fi # if [ "${GITHUB_SHA}" != "$tag_sha" ]

if [ -z "$release_url" ] ; then
	echo "Cannot figure out the release URL for ${RELEASE_NAME}"
	exit 1
fi

echo "Upload binaries to the release..."

for FILE in "$@" ; do
  FULLNAME="${FILE}"
  BASENAME="$(basename "${FILE}")"
  curl -H "Authorization: token ${RELEASE_TOKEN}" \
       -H "Accept: application/vnd.github.manifold-preview" \
       -H "Content-Type: application/octet-stream" \
       --data-binary @$FULLNAME \
       "$upload_url?name=$BASENAME"
  echo ""
done

$shatool "$@"

if [ "${GITHUB_SHA}" != "$tag_sha" ] ; then
  echo "Publish the release..."

  release_infos=$(curl -H "Authorization: token ${RELEASE_TOKEN}" \
       --data '{"draft": false}' "$release_url")

  echo "$release_infos"
fi # if [ "${GITHUB_SHA}" != "$tag_sha" ]
