########## fre:ac component makefile ##########

# Change these variables to fit your project:
TARGET	  = accuraterip
TYPE	  = verifier
VERSION	  = 1.0

FREAC_PATH = ../../..

# Enter object files here:
OBJECTS	  = accuraterip.o algorithm.o config.o database.o drive.o driveoffsets.o

# Enter additional defines here:
DEFINE	  =

# Enter additional library dependencies here:
LIBS	  =

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
CLEANCMD1 =
CLEANCMD2 =
INSTCMD1  =
INSTCMD2  = 
UINSTCMD1 =
UINSTCMD2 =

## Do not change anything below this line. ##

include $(dir $(firstword $(MAKEFILE_LIST)))/$(FREAC_PATH)/Makefile-commands
