name: freac
version: '1.1~alpha'
version-script: echo 1.1~alpha`date +"%Y%m%d"`
summary: Audio converter and CD ripper
description: |
  fre:ac is a free and open source audio converter. It comes with
  an integrated tag editor and converts between various formats.

grade: devel
confinement: strict

icon: icons/freac.png

apps:
  freac:
    command: desktop-launch freac
    desktop: share/applications/org.freac.freac.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - optical-drive
      - pulseaudio
      - removable-media
      - x11

  freaccmd:
    command: desktop-launch freaccmd
    plugs:
      - desktop
      - home
      - network
      - optical-drive
      - pulseaudio
      - removable-media
      - x11

parts:
  patches:
    source: packaging/snapcraft/patches
    plugin: dump
    prime:
      - -*

  libcdio:
    source: https://ftp.gnu.org/gnu/libcdio/libcdio-2.1.0.tar.bz2
    source-checksum: sha256/8550e9589dbd594bfac93b81ecf129b1dc9d0d51e90f9696f1b2f9b2af32712b
    plugin: autotools
    configflags: [ --prefix=/usr, --disable-cxx, --disable-example-progs, --without-cd-drive, --without-cd-info, --without-cd-read, --without-cdda-player, --without-iso-info, --without-iso-read ]
    prime:
       - usr/lib/libcdio.so*

  libcdio-paranoia:
    after: [ libcdio ]
    source: https://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+2.0.0.tar.bz2
    source-checksum: sha256/4565c18caf401083c53733e6d2847b6671ba824cff1c7792b9039693d34713c1
    plugin: autotools
    configflags: [ --prefix=/usr, --disable-cxx, --disable-example-progs ]
    prime:
      - usr/lib/libcdio_*.so*

  libfaad:
    source: https://sourceforge.net/projects/faac/files/faad2-src/faad2-2.8.0/faad2-2.8.8.tar.gz
    source-checksum: sha256/985c3fadb9789d2815e50f4ff714511c79c2710ac27a4aaaf5c0c2662141426d
    plugin: autotools
    configflags: [ --prefix=/usr ]
    prime:
       - usr/lib/libfaad.so*

  libfdk-aac:
    source: https://github.com/mstorsjo/fdk-aac/archive/v2.0.0.tar.gz
    source-checksum: sha256/6e6c7921713788e31df655911e1d42620b057180b00bf16874f5d630e1d5b9a2
    plugin: autotools
    configflags: [ --prefix=/usr ]
    prime:
      - usr/lib/libfdk-aac.so*

  libflac:
    after: [ patches, libogg ]
    source: https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.2.tar.xz
    source-checksum: sha256/91cfc3ed61dc40f47f050a109b08610667d73477af6ef36dcad31c31a4a8d53f
    plugin: autotools
    configflags: [ --prefix=/usr, --disable-cpp-libs ]
    override-build: |
      patch -p1 < $SNAPCRAFT_STAGE/flac-1.3.2-fastcrc.diff
      snapcraftctl build
    prime:
      - usr/lib/libFLAC.so*

  libmac:
    after: [ patches ]
    source: https://monkeysaudio.com/files/MAC_SDK_471.zip
    source-checksum: sha256/557adc2ec6865bfb0ba6c26d461f4c6172f1d542f71b3cf47f0cef52f99ac664
    source-subdir: .
    plugin: make
    make-parameters: [ prefix=/usr ]
    override-build: |
      if [ `lscpu | grep -i 'byte order' | awk '{ print tolower($3) }'` = "little" ]; then
        patch -p1 < $SNAPCRAFT_STAGE/mac-sdk-4.71-gcc.patch
        snapcraftctl build
      fi
    prime:
      - usr/lib/libMAC.so*

  libmp3lame:
    after: [ patches ]
    source: https://sourceforge.net/projects/lame/files/lame/3.100/lame-3.100.tar.gz
    source-checksum: sha256/ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e
    plugin: autotools
    configflags: [ --prefix=/usr, --enable-nasm, --disable-frontend ]
    override-build: |
      if [ "$SNAP_ARCH" = "amd64" ]; then
        patch -p0 < $SNAPCRAFT_STAGE/lame-3.100-sse-20171014.patch
      fi
      snapcraftctl build
    prime:
      - usr/lib/libmp3lame.so*

  libmp4v2:
    after: [ patches ]
    source: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mp4v2/mp4v2-2.0.0.tar.bz2
    source-checksum: sha256/0319b9a60b667cf10ee0ec7505eb7bdc0a2e21ca7a93db96ec5bd758e3428338
    plugin: autotools
    configflags: [ --prefix=/usr ]
    override-build: |
      patch -p1 < $SNAPCRAFT_STAGE/mp4v2-2.0.0-fixes.patch
      wget -O autoaux/config.guess "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=058639b"
      wget -O autoaux/config.sub "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=058639b"
      snapcraftctl build
    build-packages:
      - g++
      - wget
    prime:
      - usr/lib/libmp4v2.so*

  libmpg123:
    source: https://mpg123.de/download/mpg123-1.25.10.tar.bz2
    source-checksum: sha256/6c1337aee2e4bf993299851c70b7db11faec785303cfca3a5c3eb5f329ba7023
    plugin: autotools
    configflags: [ --prefix=/usr ]
    prime:
      - usr/lib/libmpg123.so*

  libogg:
    after: [ patches ]
    source: https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.3.tar.gz
    source-checksum: sha256/c2e8a485110b97550f453226ec644ebac6cb29d1caef2902c007edab4308d985
    plugin: autotools
    configflags: [ --prefix=/usr ]
    override-build: |
      patch -p1 < $SNAPCRAFT_STAGE/libogg-1.3.3-fastcrc.diff
      snapcraftctl build
    prime:
      - usr/lib/libogg.so*

  libopus:
    source: https://ftp.osuosl.org/pub/xiph/releases/opus/opus-1.3.1.tar.gz
    source-checksum: sha256/65b58e1e25b2a114157014736a3d9dfeaad8d41be1c8179866f144a2fb44ff9d
    plugin: autotools
    configflags: [ --prefix=/usr, --enable-float-approx ]
    prime:
      - usr/lib/libopus.so*

  librnnoise:
    source: https://github.com/xiph/rnnoise.git
    source-commit: 91ef401f4c3536c6de999ac609262691ec888c4c
    plugin: autotools
    configflags: [ --prefix=/usr ]
    prime:
      - usr/lib/librnnoise.so*

  libsamplerate:
    source: http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz
    source-checksum: sha256/0a7eb168e2f21353fb6d84da152e4512126f7dc48ccb0be80578c565413444c1
    plugin: autotools
    configflags: [ --prefix=/usr ]
    override-build: |
      wget -O Cfg/config.guess "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=058639b"
      wget -O Cfg/config.sub "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=058639b"
      snapcraftctl build
    build-packages:
      - wget
    prime:
      - usr/lib/libsamplerate.so*

  libsndfile:
    source: http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
    source-checksum: sha256/1ff33929f042fa333aed1e8923aa628c3ee9e1eb85512686c55092d1e5a9dfa9
    plugin: autotools
    configflags: [ --prefix=/usr ]
    prime:
      - usr/lib/libsndfile.so*

  libspeex:
    source: https://ftp.osuosl.org/pub/xiph/releases/speex/speex-1.2.0.tar.gz
    source-checksum: sha256/eaae8af0ac742dc7d542c9439ac72f1f385ce838392dc849cae4536af9210094
    plugin: autotools
    configflags: [ --prefix=/usr ]
    prime:
      - usr/lib/libspeex.so*

  libvorbis:
    after: [ patches, libogg ]
    source: https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.6.tar.gz
    source-checksum: sha256/6ed40e0241089a42c48604dc00e362beee00036af2d8b3f46338031c9e0351cb
    plugin: autotools
    configflags: [ --prefix=/usr ]
    override-build: |
      patch -p1 < $SNAPCRAFT_STAGE/libvorbis-1.3.6-aotuv-b6.03.patch
      if [ "$SNAP_ARCH" = "amd64" ]; then
        patch -p1 < $SNAPCRAFT_STAGE/libvorbis-1.3.6-aotuv-b6.03-lancer.patch
      fi
      snapcraftctl build
    prime:
      - usr/lib/libvorbis*.so*

  ffmpeg:
    source: https://ffmpeg.org/releases/ffmpeg-4.1.tar.bz2
    source-checksum: sha256/b684fb43244a5c4caae652af9022ed5d85ce15210835bce054a33fb26033a1a5
    plugin: autotools
    configflags: [ --prefix=/usr, --disable-autodetect, --enable-gpl, --enable-small, --enable-runtime-cpudetect ]
    build-packages:
      - yasm
    prime:
      - usr/bin/ffmpeg

  smooth:
    after: [ curl, desktop-gtk3, patches ]
    source: https://github.com/enzo1982/smooth.git
    plugin: make
    make-parameters: [ prefix= ]
    build-packages:
      - g++
      - libbz2-dev
      - libfribidi-dev
      - libjpeg8-dev
      - libxml2-dev
    stage-packages:
      - libbz2-1.0
      - libfribidi0
      - libjpeg8
      - libxml2

  boca:
    after: [ libcdio-paranoia, smooth ]
    source: https://github.com/enzo1982/BoCA.git
    plugin: make
    make-parameters: [ prefix= ]
    override-build: |
      patch -p1 < $SNAPCRAFT_STAGE/freac-cdk-1.1-alpha-snap.patch
      snapcraftctl build
    build-packages:
      - libpulse-dev
      - liburiparser-dev
    stage-packages:
      - libpulse0
      - librubberband2v5
      - liburiparser1
      - musepack-tools
      - wavpack

  freac:
    after: [ boca ]
    source: https://github.com/enzo1982/freac.git
    plugin: make
    make-parameters: [ prefix=, CXXFLAGS+=-DFREAC_DATE=\"$(shell date +"%Y%m%d")\" ]
    build-packages:
      - libudev-dev
    stage-packages:
      - libudev1
